### ISSUE TITLE
Future of `@local` decorator. Consolidate issues here

### ISSUE THREAD

**Issue by cowlicks** [enthought/distarray#170]
There are several open issues about the future of the `@local` decorator. This issue is for consolidating them and deciding a path forward. To summarize what has been said in other issues:
- [ ] change its name to avoid conflicts with the `local/` stuff.
- [ ] Refactor `@local` to use `@remote` decorator #22.
  `@remote` is:
  1) Is tied to a particular view at import time: you call with `@remote(view)`
  2) Doesn't allow calling other `@remote` functions from within a `@remote` function
  3) Doesn't allow returning proxy objects (yet?)
- [ ] Use IPython-parallel's reference-/proxy-object support (when implemented) #25 
  Brian and Min mentioned the possibility of adding
  
  1) the ability to return reference objects, or even
  2) support for different types of proxy objects
  
  to IPython-parallel. If and when these are implemented, DistArrays and @local should      work with these.
- [ ] Replace `execute` statements with `@local` functions #22 
  
  There are a lot of `execute` statements in the current code of the following form which we should replace with `@local` decorators.

```
    %s = distarray.%s(%s)
```
